In [1]:
import json
import pandas as pd

data_file = open("yelp_academic_dataset_review.json")
data = []

for i in range(2000):
    line = data_file.readline()
    if not line:
        break
    data.append(json.loads(line))

data_file.close()

review_df = pd.DataFrame(data)
review_df.head()

,0,1,2,3,4,5,6,7,8,9,...,99990,99991,99992,99993,99994,99995,99996,99997,99998,99999
0,"{'stars': 3.0, 'text': 'If you decide to eat h...","{'stars': 5.0, 'text': 'I've taken a lot of sp...","{'stars': 3.0, 'text': 'Family diner. Had the ...","{'stars': 5.0, 'text': 'Wow! Yummy, different...","{'stars': 4.0, 'text': 'Cute interior and owne...","{'stars': 1.0, 'text': 'I am a long term frequ...","{'stars': 5.0, 'text': 'Loved this tour! I gra...","{'stars': 5.0, 'text': 'Amazingly amazing wing...","{'stars': 3.0, 'text': 'This easter instead of...","{'stars': 3.0, 'text': 'Had a party of 6 here ...",...,"{'stars': 3.0, 'text': 'It's tough to review t...","{'stars': 1.0, 'text': 'Not hygienic and Fresh...","{'stars': 4.0, 'text': 'Less greasy than 5 Guy...","{'stars': 4.0, 'text': 'We liked everything ab...","{'stars': 2.0, 'text': 'I had a late lunch wit...","{'stars': 4.0, 'text': 'Came here for lunch wi...","{'stars': 1.0, 'text': 'The equipment is so ol...","{'stars': 4.0, 'text': 'This is one of my favo...","{'stars': 2.0, 'text': 'Came here for brunch -...","{'stars': 5.0, 'text': 'Came in for my 5-6 mon..."

In [ ]:
# Nos quedamos solo con las reseñas que marcan 1 o 5 estrellas para conseguir mejores resultados en el entrenamiento.
review_df = review_df[(review_df['stars'] == 1) | (review_df['stars'] == 5)]

# Se reemplazan los valores en la columna stars de 1 a 0 y 5 a 1 para entrenar el modelo
review_df['liked'] = review_df['stars'].replace({1:0, 5:1})

# Filtramos solo para quedarnos solo con el texto de la reseña y la estrella
review_df = review_df[['text', 'liked']]

print("Reviews for training:",len(review_df))
review_df.head()